#!/bin/bash

echo "AI CyberX Platform - Startup Summary"
echo "===================================="
echo ""

# Check current status
echo "Current service status:"
docker ps | grep cyberx || echo "No cyberx services running yet"

echo ""
echo "Database services status:"
docker ps | grep -E "(postgres|redis)" || echo "No database services running"

echo ""
echo "Available images:"
docker images | grep -E "(cyberx|postgres|redis)" || echo "Checking images..."

echo ""
echo "=========================================="
echo "STARTUP INSTRUCTIONS"
echo "=========================================="
echo ""
echo "The AI CyberX platform requires Docker to build and run."
echo ""
echo "Quick Start:"
echo "1. Make sure Docker is running"
echo "2. Run: docker compose -f docker-compose-root.yml up -d"
echo ""
echo "Full Build (takes time due to many dependencies):"
echo "1. Build backend: docker build -t cyberx-backend -f infrastructure/docker/Dockerfile.backend backend"
echo "2. Build frontend: docker build -t cyberx-frontend -f infrastructure/docker/Dockerfile.frontend frontend"
echo "3. Start services: docker compose -f docker-compose-root.yml up -d"
echo ""
echo "Access the platform at:"
echo "  Frontend: http://localhost:3000"
echo "  Backend:  http://localhost:8000"
echo "  API Docs: http://localhost:8000/docs"
echo ""
echo "Troubleshooting:"
echo "- If ports are in use, modify docker-compose-root.yml"
echo "- Check logs: docker compose -f docker-compose-root.yml logs -f"
echo "- Clean up: docker compose -f docker-compose-root.yml down"
echo ""
echo "The platform includes:"
echo "✓ AI Teaching Engine (OpenAI/Anthropic/Mistral/Gemini)"
echo "✓ RAG Knowledge Base (ChromaDB)"
echo "✓ Docker-based Lab Environments"
echo "✓ Skill Tracking System"
echo "✓ Adaptive Learning Paths"
echo "✓ Comprehensive Security Features"