version: "3.9"

services:
  # PostgreSQL Database
  postgres:
    image: docker.io/postgres:15-alpine
    container_name: cyberx-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?POSTGRES_USER is required}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
      POSTGRES_DB: ${POSTGRES_DB:-cyberx}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cyberx -d cyberx"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cyberx-network

  # Redis Cache
  redis:
    image: docker.io/redis:7-alpine
    container_name: cyberx-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cyberx-network

  # Backend API
  backend:
    build:
      context: ../../backend
      dockerfile: ../infrastructure/podman/Dockerfile.backend
    container_name: cyberx-backend
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-cyberx}
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY:?SECRET_KEY is required}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
      - DEFAULT_AI_MODEL=mistral-large-latest
      - PODMAN_SOCKET=/run/podman/podman.sock
      - DEBUG=false
      - CORS_ORIGINS=["http://185.182.187.146:3000","http://185.182.187.146","http://localhost:3000"]
    volumes:
      - ../../data:/app/data
      - /run/podman/podman.sock:/run/podman/podman.sock:ro
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - cyberx-network

  # Frontend
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../infrastructure/podman/Dockerfile.frontend
      args:
        - NEXT_PUBLIC_API_URL=http://185.182.187.146:8000
    container_name: cyberx-frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=http://185.182.187.146:8000
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - backend
    networks:
      - cyberx-network

volumes:
  postgres_data:
  redis_data:

networks:
  cyberx-network:
    driver: bridge
